import os.path

generatedExtensions = ('.hi', '.o', '.hp', '.ps', '.aux')

for testSource in Glob('*_test_*.hs'):
    testRoot = os.path.splitext(testSource.name)[0]
    sources = (testSource.name, 'Factorial.hs')
    compilationProducts = tuple(os.path.splitext(item)[0] + extension for item in sources for extension in generatedExtensions)
    Command(testRoot, sources, 'ghc --make -O -o $TARGET $SOURCES')
    SideEffect(compilationProducts,  testRoot)
    Clean(testRoot, compilationProducts)
