import pathlib
import os

root = 'Factorial_Chapel'

test_root = root + '_Test'

test = Command(
    test_root,
    [str(pathlib.Path('src') / (root + '.chpl')), str(pathlib.Path('test') / (test_root + '.chpl'))],
    f'chpl -o $TARGET --main-module {test_root} $SOURCES',
    ENV=os.environ,
)
Command('test', test, './$SOURCE')

Clean('.', Glob('*~') + Glob('*/*~'))
