import os
import pathlib
import subprocess

built = pathlib.Path(os.environ['HOME']) / 'Built'
include_path = built / 'include' / 'd'
library_path = built / 'lib'

sources = Glob('source/*.d')

testEnvironment = Environment(
    tools=['ldc', 'link'],
    DFLAGS=['-unittest'],
    DPATH=[include_path.as_posix()],
    DLINKFLAGS=['-link-defaultlib-shared'],
    ENV=os.environ,
    LIBPATH=[library_path.as_posix()],
    LIBS=['unit-threaded'],
)

ut_main = testEnvironment.Command('ut_main.d', sources, 'gen-ut-main -f $TARGET source')

factorial_test = testEnvironment.ProgramAllAtOnce('factorial_test', sources + ut_main)
SideEffect('factorial_test.o', factorial_test)

Default(Command('test', factorial_test, f'LD_LIBRARY_PATH={library_path}./$SOURCE'))

Clean('.', ut_main)
